spring:
  application:
    name: Buzzer Buttons
  datasource:
    url: jdbc:postgresql://localhost:5432/${BUZZERS_DB_DB}
    username: ${BUZZERS_DB_USER}
    password: ${BUZZERS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
  websocket:
    enabled: true

jwt:
  expiration: 600000
  refresh-expiration: 86400000

#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG

server:
  port: ${BUZZERS_PORT}