spring:
  application:
    name: Buzzer Buttons
  datasource:
    url: ${BUZZERS_DB_HOST}${BUZZERS_DB_DB}
    username: ${BUZZERS_DB_USER}
    password: ${BUZZERS_DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  websocket:
    enabled: true

jwt:
  expiration: 600000
  refresh-expiration: 86400000

#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG

server:
  port: ${BUZZERS_SERVER_PORT}