spring:

  application:
    name: Buzzer Buttons
  datasource:
    url: jdbc:postgresql://localhost:5432/${BUZZERS_DB_DB}
    username: ${BUZZERS_DB_USER}
    password: ${BUZZERS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: 600000
  refresh-expiration: 86400000


server:
  port: ${BUZZERS_PORT}