spring:
  application:
    name: Buzzer Buttons
  profiles:
    active: ${BUZZERS_PROFILE}
  datasource:
    url: ${BUZZERS_DB_HOST}${BUZZERS_DB_DB}
    username: ${BUZZERS_DB_USER}
    password: ${BUZZERS_DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  websocket:
    enabled: true
  mail:
    host: ${BUZZERS_MAIL_HOST}
    port: ${BUZZERS_MAIL_PORT}
    username: ${BUZZERS_MAIL_USER}
    password: ${BUZZERS_MAIL_PWD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: ${BUZZERS_MAIL_HOST}
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  expiration: 1800000

#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG

server:
  port: ${BUZZERS_SERVER_PORT}
